### ISSUE TITLE
Code not Finding .exe files

### ISSUE THREAD

**Issue by bmartin598** [furrysalamander/mini-map-maker#3]
When I run the convert.exe it gets all the way through unzipping. When it finishes unzipping it tries to run GridSuraceCreate64.exe and DTM2ASCII.exe and says the do not exist. This also occurs when I try to use the .py version of convert program. 

My downloadlist.txt is attached below. Let me know if you need anything else to troubleshoot.

[downloadlist.txt](https://github.com/furrysalamander/mini-map-maker/files/5902012/downloadlist.txt)

**Comment by bmartin598** [comment]
Figured out how to fix this. Had to add the file directory to my environment via the control center

**Comment by furrysalamander** [comment]
So glad you got this figured out!  :)  Hoping to get more features implemented as soon as I get caught up on homework.
